# Generated by Django 3.1.7 on 2021-03-02 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caducidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('vida_prod', models.CharField(help_text='Tiempo de vida del producto', max_length=30, unique=True)),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_caducidad_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_caducidad_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Caducidades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100, unique=True)),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_categoria_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_categoria_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Decoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('decoracion', models.CharField(help_text='Descripción de la decoración', max_length=30, unique=True)),
                ('estilo', models.CharField(help_text='descripcion del estilo', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='decoracion/%Y/%m/%d')),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_decoracion_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_decoracion_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Decoraciones',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=100, unique=True)),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_marca_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_marca_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre de la Oferta', max_length=30, unique=True)),
                ('precioOferta', models.FloatField(default=0)),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_oferta_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_oferta_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Unidad de Medida', max_length=100, unique=True)),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_unidadmedida_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_unidadmedida_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unidad de medidas',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Sub-Categoría', max_length=100, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.categoria')),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_subcategoria_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_subcategoria_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Categorias',
                'unique_together': {('categoria', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('sabor', models.CharField(help_text='Descripción del Sabor', max_length=30, unique=True)),
                ('descripcion', models.CharField(help_text='observaciones', max_length=100, unique=True)),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_sabor_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_sabor_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sabores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('f_c', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_m', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_barra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('existencia', models.IntegerField(default=0)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('caducidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.caducidad')),
                ('decoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.decoracion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.marca')),
                ('oferta', models.ManyToManyField(to='inv.Oferta')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.sabor')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.subcategoria')),
                ('u_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_producto_creation', to=settings.AUTH_USER_MODEL)),
                ('u_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_producto_updated', to=settings.AUTH_USER_MODEL)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.unidadmedida')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
